// Week3_4-FrontendDevelopment/Handson_08/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="course-card">
    <h2>{{ name }}</h2>

    <p><strong>Code:</strong> {{ code }}</p>

    <p><strong>Credits:</strong> {{ credits }}</p>

    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})
</script>

// Week3_4-FrontendDevelopment/Handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: false,
  templateUrl: './course-card.html',
  styleUrls: ['./course-card.css']
})
export class CourseCard {

  @Input() name!: string;

  @Input() code!: string;

  @Input() credits!: number;

  @Input() grade!: string;

}
